FROM python:3.12

WORKDIR /app

COPY requirements-embedding.txt /app
RUN pip install --no-cache-dir -r requirements-embedding.txt

COPY . /app

EXPOSE 3214

ENV EMBEDDING_ENABLED=1

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3214"]
