FROM python:3.12

WORKDIR /app

RUN apt update -y && apt install -y ffmpeg

COPY requirements-embedding-whisper.txt /app
RUN pip install --no-cache-dir -r requirements-embedding-whisper.txt

COPY . /app

EXPOSE 3214

ENV EMBEDDING_ENABLED=1
ENV TRANSCRIPTION_ENABLED=1
CMD ["uvicorn", "main:app", "--workers", "1", "--host", "0.0.0.0", "--port", "3214"]
